<a href="https://colab.research.google.com/github/shazoop/KG-Embeddings/blob/main/Paper2_experiments.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [19]:
from GETSv2 import *

In [20]:
book_size = [16,32,64,128,264,512,1024,2048]
edge_list = [8,16,32,48,64,128,256,512]

In [21]:
vertex_dim = 16
vertex_num = 64
num_edge = 64
num_trials = 200

In [12]:
#Effect of codebook size and resampling.

cor_edgeQ, incor_edgeQ, cor_compQ, incor_compQ = testing_code(vertex_dim, vertex_num, book_size, num_edge, num_trials)

In [13]:
corEQ = np.array(cor_edgeQ)
incorEQ = np.array(incor_edgeQ)
corEC = np.array(cor_compQ)
incorEC = np.array(incor_compQ)

In [14]:
corEQ

array([[0.14863491, 0.40214799],
       [1.03645676, 0.34685208],
       [0.99955013, 0.54376644],
       [1.09080188, 0.49119874],
       [1.00392117, 0.49517444],
       [0.99406123, 0.44864309],
       [1.06648805, 0.4817906 ]])

In [15]:
incorEQ

array([[-0.87157399,  0.36327815],
       [ 0.04237042,  0.32514274],
       [-0.04299314,  0.56460814],
       [ 0.03162181,  0.48161653],
       [-0.00846701,  0.50870293],
       [ 0.04864029,  0.43738976],
       [-0.06009907,  0.48741878]])

In [16]:
corEC

array([[-0.16867558,  2.08022464],
       [ 0.47707931,  0.96389323],
       [ 0.99329181,  1.4271058 ],
       [ 0.87739378,  1.25480962],
       [ 0.87362679,  1.25003499],
       [ 0.77742285,  1.28656379],
       [ 0.82068269,  1.28090219]])

In [17]:
incorEC

array([[-0.4363279 ,  2.10610662],
       [ 0.03531659,  1.24677936],
       [ 0.03420855,  1.22501768],
       [ 0.06565612,  1.06337042],
       [ 0.0243904 ,  1.07376786],
       [ 0.05952736,  1.03855711],
       [-0.02815048,  0.96918781]])

In [22]:
cor_edgeQ, incor_edgeQ, cor_compQ, incor_compQ = testing_R(vertex_dim, vertex_num, edge_list, num_trials)

In [ ]:
cor_edgeQ = np.array(cor_edgeQ)
incor_edgeQ = np.array(incor_edgeQ)

In [25]:
cor_compQ = np.array(cor_compQ)/16

In [27]:
cor_compQ

array([[   0.9025    ,    3.44381602],
       [  -1.025     ,    6.31575411],
       [  -3.85875   ,   12.68578381],
       [  -5.875     ,   18.71204492],
       [  -4.88375   ,   23.41896771],
       [ -21.915     ,   52.05176174],
       [ -64.82125   ,  104.55906637],
       [-242.63375   ,  222.20067771]])

In [ ]:
fig1, axs = plt.subplots(1,2)
fig1.suptitle('Edge Query')
fig1.text(0.5, 0.035, 'Vertex Codebook Size', ha='center')
fig1.text(0.04, 0.5, 'Average Score', va='center', rotation='vertical')
axs[0].plot(edge_list,cor_edgeQ[:,0], marker = 'o')
axs[0].axhline(y=1, color = 'r', linestyle = '-')
axs[0].set_title('Correct')
axs[1].plot(edge_list,incor_edgeQ[:,0], marker = 'o')
axs[1].axhline(y=0, color = 'r', linestyle = '-')
axs[1].set_title('Incorrect')

In [ ]:
fig1, axs = plt.subplots(1,2)
fig1.suptitle('Edge Composition')
fig1.text(0.5, 0.035, '# of edges', ha='center')
fig1.text(0.04, 0.5, 'score deviation', va='center', rotation='vertical')
axs[0].plot(edge_list,cor_compQ, marker = 'o')
axs[0].axhline(y=1, color = 'r', linestyle = '-')
axs[0].set_title('Correct')
axs[1].plot(edge_list,incor_compQ, marker = 'o')
axs[1].axhline(y=1, color = 'r', linestyle = '-')
axs[1].set_title('Incorrect')

In [ ]:
cor_edgeQ_R, incor_edgeQ_R, cor_compQ_R, incor_compQ_R = testing_R(vertex_dim, vertex_num, edge_list, num_trials)

In [ ]:
fig1, axs = plt.subplots(1,2)
fig1.suptitle('Edge Query')
fig1.text(0.5, 0.035, '# of edges', ha='center')
fig1.text(0.04, 0.5, 'score deviation', va='center', rotation='vertical')
axs[0].plot(edge_list,cor_edgeQ_R, marker = 'o')
axs[0].axhline(y=256, color = 'r', linestyle = '-')
axs[0].set_title('Correct')
axs[1].plot(edge_list,incor_edgeQ_R, marker = 'o')
axs[1].axhline(y=0, color = 'r', linestyle = '-')
axs[1].set_title('Incorrect')

In [ ]:
fig1, axs = plt.subplots(1,2)
fig1.suptitle('Edge Composition')
fig1.text(0.5, 0.035, '# of edges', ha='center')
fig1.text(0.04, 0.5, 'score deviation', va='center', rotation='vertical')
axs[0].plot(edge_list,cor_compQ_R, marker = 'o')
axs[0].axhline(y=256, color = 'r', linestyle = '-')
axs[0].set_title('Correct')
axs[1].plot(edge_list,incor_compQ_R, marker = 'o')
axs[1].axhline(y=0, color = 'r', linestyle = '-')
axs[1].set_title('Incorrect')

In [ ]:
test_code = vertex_code_R(16,20)
generate_graph_R(test_code,40)

In [ ]:
def generate_graph_R(codebook, num_edges):
  n,d = codebook.shape[0], codebook.shape[1]
  graph = 0
  for i in range(num_edges):
    d_ix, c_ix = rand.randint(0,n-1), rand.randint(0,n-1)
    dom, cod = codebook[d_ix], codebook[c_ix]
    graph  = graph + (dom*cod)
  return(graph)

In [ ]:
codebook = test_code

In [ ]:
n,d = codebook.shape[0], codebook.shape[1]


In [ ]:
graph = 0
for i in range(4):
  d_ix, c_ix = rand.randint(0,n-1), rand.randint(0,n-1)
  dom, cod = codebook[d_ix], codebook[c_ix]
  graph  = graph + (dom*cod)


In [ ]:
  d_ix, c_ix = rand.randint(0,n-1), rand.randint(0,n-1)
  dom, cod = codebook[d_ix], codebook[c_ix]

In [ ]:
graph

In [ ]:
128**2/16**2